#!/bin/bash

systempath=$1
thispath=`cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd`

# Debloat 
rm -rf $1/priv-app/SoundPicker
rm -rf $1/app/PacProcessor
rm -rf $1/app/PartnerBookmarksProvider
rm -rf $1/product/priv-app/AmbientSensePrebuilt
rm -rf $1/priv-app/ContactsProvider
rm -rf $1/priv-app/CellBroadcastLegacyApp
rm -rf $1/product/priv-app/HotwordEnrollmentXGoogleRT5514
rm -rf $1/product/priv-app/ScribePrebuilt
rm -rf $1/priv-app/GooglePackageInstaller
rm -rf $1/priv-app/TelephonyProvider
rm -rf $1/app/QtiTelephonyService
rm -rf $1/product/app/YouTube
rm -rf $1/product/priv-app/SprintDM
rm -rf $1/product/app/Music2
rm -rf $1/priv-app/qcrilmsgtunnel
rm -rf $1/priv-app/DynamicSystemInstallationService
rm -rf $1/product/app/Maps
rm -rf $1/priv-app/DownloadProviderUi
rm -rf $1/priv-app/NetworkPermissionConfigGoogle
rm -rf $1/app/Stk
rm -rf $1/priv-app/TagGoogle
rm -rf $1/priv-app/Shell
rm -rf $1/product/app/MobileFeliCaMenuMainApp
rm -rf $1/priv-app/CNEService
rm -rf $1/app/SecureElement
rm -rf $1/app/CompanionDeviceManager
rm -rf $1/product/priv-app/CarrierServices
rm -rf $1/app/EasterEgg
rm -rf $1/product/app/GoogleCamera
rm -rf $1/priv-app/MmsService
rm -rf $1/product/app/GoogleTTS
rm -rf $1/priv-app/BuiltInPrintService
rm -rf $1/product/app/VZWAPNLib
rm -rf $1/app/CaptivePortalLoginGoogle
rm -rf $1/app/atfwd
rm -rf $1/priv-app/BlockedNumberProvider
rm -rf $1/app/NfcNci
rm -rf $1/product/priv-app/HelpRtcPrebuilt
rm -rf $1/product/priv-app/SprintDM
rm -rf $1/product/priv-app/ScribePrebuilt
rm -rf $1/product/priv-app/TurboPrebuilt
rm -rf $1/product/priv-app/DCMO
rm -rf $1/product/app/VZWAPNLib
rm -rf $1/product/app/Drive
rm -rf $1/priv-app/TeleService
rm -rf $1/product/priv-app/SprintHM
rm -rf $1/product/app/CalendarGooglePrebuilt
rm -rf $1/priv-app/SharedStorageBackup
rm -rf $1/app/datastatusnotification
rm -rf $1/priv-app/DocumentsUIGoogle
rm -rf $1/priv-app/CallLogBackup
rm -rf $1/app/PrintSpooler
rm -rf $1/product/app/SafetyRegulatoryInfo
rm -rf $1/product/app/SoundAmplifierPrebuilt
rm -rf $1/app/LiveWallpapersPicker
rm -rf $1/priv-app/StatementService
rm -rf $1/product/app/MobileFeliCaClient
rm -rf $1/product/priv-app/EuiccGoogle
rm -rf $1/product/app/MobileFeliCaMenuMainApp
rm -rf $1/app/HTMLViewer
rm -rf $1/app/NfcNci
rm -rf $1/priv-app/Traceur
rm -rf $1/priv-app/BackupRestoreConfirmation
rm -rf $1/app/uimremoteserver
rm -rf $1/priv-app/NetworkStackGoogle
rm -rf $1/product/app/PrebuiltGmail
rm -rf $1/priv-app/MusicFX
rm -rf $1/product/priv-app/HotwordEnrollmentXGoogleRT5514
rm -rf $1/product/priv-app/ConnMO
rm -rf $1/app/GooglePrintRecommendationService
rm -rf $1/product/priv-app/SafetyHubLprPrebuilt
rm -rf $1/product/app/YouTube
rm -rf $1/priv-app/BuiltInPrintService
rm -rf $1/product/app/GoogleTTS
rm -rf $1/product/priv-app/HelpRtcPrebuilt
rm -rf $1/priv-app/BluetoothMidiService
rm -rf $1/app/uimremoteclient
rm -rf $1/app/BasicDreams
rm -rf $1/product/priv-app/CarrierServices
rm -rf $1/product/priv-app/EuiccGoogle
rm -rf $1/app/ims
rm -rf $1/priv-app/ProxyHandler
rm -rf $1/app/uceShimService
rm -rf $1/product/app/SafetyRegulatoryInfo
rm -rf $1/priv-app/LocalTransport
rm -rf $1/app/BluetoothMidiService
rm -rf $1/product/priv-app/TipsPrebuilt
rm -rf $1/app/CameraExtensionsProxy
rm -rf $1/product/app/PrebuiltGmail
rm -rf $1/product/app/Drive
rm -rf $1/app/CertInstaller

# Fix Files-DocumentsUI
rm -rf $1/product/overlay/PixelDocumentsUIOverlay

# Hotword
rm -rf $1/product/priv-app/HotwordEnrollment*
rm -rf $1/system_ext/framework/com.android.hotwordenrollment*
rm -rf $1/system_ext/framework/oat/arm/com.android.hotwordenrollment*
rm -rf $1/system_ext/framework/oat/arm64/com.android.hotwordenrollment*
